In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [5]:
movies = movies.merge(credits, on='title')

In [6]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [7]:
# genres
# id
# keywords
# title
# overview
# cast
# crew

movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [8]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [10]:
movies.dropna(inplace=True)

In [11]:
movies.duplicated().sum()

0

In [12]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [13]:
# '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
# ['Action', 'Adventure', 'Fantasy', 'Scify']

In [17]:
import ast

def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [18]:
movies['genres'] = movies['genres'].apply(convert)

In [19]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
movies['keywords'] = movies['keywords'].apply(convert)

In [21]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [22]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [23]:
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
        else:
            break
    return L

In [24]:
movies['cast'] = movies['cast'].apply(convert3)

In [25]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [26]:
def fetch_director(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [27]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [28]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [29]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [30]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [31]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [32]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ", "") for i in x])

In [33]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [34]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [35]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [36]:
new_df = movies[['movie_id', 'title', 'tags']]

In [37]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_11844\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [38]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [39]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenLang MichelleRodriguez GiovanniRibisi JoelDavidMoore CCHPounder WesStudi LazAlonso DileepRao MattGerald SeanAnthonyMoran JasonWhyte ScottLawrence KellyKilgour JamesPatrickPitt SeanPatrickMurphy PeterDillon KevinDorman KelsonHenderson DavidVanHorn JacobTomuri MichaelBlain-Rozgay JonCurry LukeHawker WoodySchultz PeterMensah SoniaYee JahnelCurfman IlramChoi KylaWarren LisaRoumain DebraWilson ChrisMala TaylorKibby JodieLandau JulieLamm CullenB.Madden JosephBradyMadden FrankieTorres AustinWilson SaraWilson TamicaWashington-Miller LucyBriant NathanMeister GerryBlair MatthewChamberlain PaulYates WrayWilson JamesGaylyn MelvinLenoClarkIII CarvonFutrell BrandonJelkes MicahMoch HanniyahMuhammad ChristopherNolen ChristaOliver AprilMarieThomas BravitaA.Threatt ColinBleasdale MikeBodnar MattClayton NicoleDionne JamieHarrison AllanHenry AnthonyIngruber AshleyJeffery DeanKnowsley JosephMika-Hunt TerryNotary KaiPantano LoganPithyou StuartPollock Raja GarethRuck RhianSheehan T.J.Storm JodieTaylor AliciaVela-Bailey RichardWhiteside NikieZambo JuleneRenee JamesCameron'

In [40]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_11844\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [41]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [42]:
import nltk

In [43]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [44]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [45]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_11844\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [46]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav stephenlang michellerodriguez giovanniribisi joeldavidmoor cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyt scottlawr kellykilgour jamespatrickpitt seanpatrickmurphi peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurri lukehawk woodyschultz petermensah soniaye jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibbi jodielandau julielamm cullenb.madden josephbradymadden frankietorr austinwilson sarawilson tamicawashington-mil lucybri nathanmeist gerryblair matthewchamberlain paulyat wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrel brandonjelk micahmoch hanniyahmuhammad christophernolen christaoliv aprilmariethoma bravitaa.threatt colinbleasdal mikebodnar mattclayton nicoledionn jamieharrison allanhenri anthonyingrub ashleyjefferi deanknowsley josephmika-hunt terrynotari kaipantano loganpithy stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhitesid nikiezambo julenerene jamescameron'

In [47]:
new_df['tags'][1]

"captain barbossa, long believ to be dead, ha come back to life and is head to the edg of the earth with will turner and elizabeth swann. but noth is quit as it seems. adventur fantasi action ocean drugabus exoticisland eastindiatradingcompani loveofone'slif traitor shipwreck strongwoman ship allianc calypso afterlif fighter pirat swashbuckl aftercreditssting johnnydepp orlandobloom keiraknightley stellanskarsgÃ¥rd chowyun-fat billnighi geoffreyrush jackdavenport kevinmcn tomholland naomieharri jonathanpryc keithrichard leearenberg mackenziecrook gregelli davidbaili martinklebba davidschofield laurenmah vanessabranch angusbarnett gilesnew reggiele dominicscottkay takayofisch davidmeuni ho-kwants andybeckwith peterdonaldbadalamentiii christophers.capp keithrichard hakeemkae-kazim ghassanmassoud goreverbinski"

In [48]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [49]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [50]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [51]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zoo', 'zooeydeschanel', 'zoÃ«kravitz'],
      dtype=object)

In [52]:
['loved', 'loving', 'love'
['love', 'love', 'love']]

<>:1: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\Ahmed\AppData\Local\Temp\ipykernel_11844\2999454730.py:1: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  ['loved', 'loving', 'love'
C:\Users\Ahmed\AppData\Local\Temp\ipykernel_11844\2999454730.py:1: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  ['loved', 'loving', 'love'
C:\Users\Ahmed\AppData\Local\Temp\ipykernel_11844\2999454730.py:1: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  ['loved', 'loving', 'love'
C:\Users\Ahmed\AppData\Local\Temp\ipykernel_11844\2999454730.py:1: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  ['loved', 'loving', 'love'
C:\Users\Ahmed\AppData\Local\Temp\ipykernel_11844\2999454730.py:1: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  ['loved', 'loving', 'love'

TypeError: string indices must be integers, not 'tuple'

In [53]:
ps.stem('dancing')

'danc'

In [54]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez giovanniribisi joeldavidmoore cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyte scottlawrence kellykilgour jamespatrickpitt seanpatrickmurphy peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurry lukehawker woodyschultz petermensah soniayee jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibby jodielandau julielamm cullenb.madden josephbradymadden frankietorres austinwilson sarawilson tamicawashington-miller lucybriant nathanmeister gerryblair matthewchamberlain paulyates wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrell brandonjelkes micahmoch hanniyahmuhammad christophernolen christaoliver aprilmariethomas bravitaa.threatt colinbleasdale mikebodnar mattclayton nicoledionne jamieharrison allanhenry anthonyingruber ashleyjeffery deanknowsley josephmika-hunt terrynotary kaipantano loganpithyou stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhiteside nikiezambo julenerenee jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav stephenlang michellerodriguez giovanniribisi joeldavidmoor cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyt scottlawr kellykilgour jamespatrickpitt seanpatrickmurphi peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurri lukehawk woodyschultz petermensah soniaye jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibbi jodielandau julielamm cullenb.madden josephbradymadden frankietorr austinwilson sarawilson tamicawashington-mil lucybri nathanmeist gerryblair matthewchamberlain paulyat wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrel brandonjelk micahmoch hanniyahmuhammad christophernolen christaoliv aprilmariethoma bravitaa.threatt colinbleasdal mikebodnar mattclayton nicoledionn jamieharrison allanhenri anthonyingrub ashleyjefferi deanknowsley josephmika-hunt terrynotari kaipantano loganpithy stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhitesid nikiezambo julenerene jamescameron'

In [55]:
from sklearn.metrics.pairwise import cosine_similarity

In [56]:
similarity = cosine_similarity(vectors)

In [57]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])[1:6]

[(1216, 0.27028123880866767),
 (582, 0.23162743094465488),
 (2333, 0.22996655275195),
 (3730, 0.22498852128662872),
 (507, 0.22438727760202976)]

In [58]:
sorted(similarity[0], reverse=True)

[0.9999999999999998,
 0.27028123880866767,
 0.23162743094465488,
 0.22996655275195,
 0.22498852128662872,
 0.22438727760202976,
 0.22305671869347438,
 0.22010219462003333,
 0.2175970699446223,
 0.20751433915982237,
 0.20695933859617893,
 0.20691022044226628,
 0.20100756305184242,
 0.19968076595771794,
 0.19790977371009408,
 0.19596237883454903,
 0.19462473604038075,
 0.1938287215142766,
 0.1928473039599675,
 0.1928473039599675,
 0.19145989526687088,
 0.18540496217739155,
 0.18463723646899916,
 0.18281810603178267,
 0.18098069149825674,
 0.1809806914982567,
 0.17837651700316892,
 0.1776672636296754,
 0.175919798853417,
 0.17588161767036212,
 0.17407765595569785,
 0.17407765595569785,
 0.17348855898381338,
 0.17056057308448835,
 0.16898159235484367,
 0.1688801323682996,
 0.16854996561581054,
 0.1682904582015223,
 0.1682904582015223,
 0.16685595311797868,
 0.16351748504193214,
 0.16262312563634837,
 0.160930171455096,
 0.1599005372667078,
 0.1599005372667078,
 0.15909090909090912,
 0.15745916432444343,
 0.15745916432444343,
 0.15731330124142318,
 0.15701373439577193,
 0.15559397856603546,
 0.15392982399673985,
 0.15386436372416595,
 0.15075567228888181,
 0.15075567228888181,
 0.1507556722888818,
 0.1492405014489273,
 0.1492405014489273,
 0.1487044791289829,
 0.1487044791289829,
 0.14782809899727067,
 0.14782809899727067,
 0.14777011582226215,
 0.14716573653773893,
 0.14673479641335554,
 0.1463423517512409,
 0.14625448482542613,
 0.14519080172812554,
 0.14506471329641488,
 0.14484136487558028,
 0.14484136487558028,
 0.1446354779699756,
 0.14245072057454744,
 0.1421338109037403,
 0.14126448280440335,
 0.1411569346481171,
 0.1399731277389636,
 0.13977653617040256,
 0.13762047064079508,
 0.1374416265488099,
 0.13623731522826651,
 0.13483997249264842,
 0.13483997249264842,
 0.13483997249264842,
 0.13402192668680965,
 0.1340050420345616,
 0.13336626734231613,
 0.13336626734231613,
 0.13336626734231613,
 0.1332504477222565,
 0.1315903389919538,
 0.1315903389919538,
 0.1315903389919538,
 0.1305582419667734,
 0.1305582419667734,
 0.13005121775247103,
 0.1292719224987548,
 0.1292719224987548,
 0.12921914767618442,
 0.12921914767618442,
 0.1292191476761844,
 0.12892415701965754,
 0.128564869306645,
 0.12792042981336627,
 0.12792042981336627,
 0.12741179785940637,
 0.12741179785940637,
 0.1266600992762247,
 0.1257389226923863,
 0.1257389226923863,
 0.1257389226923863,
 0.1256297269074015,
 0.12543630150106364,
 0.12436708454077278,
 0.12424730498438732,
 0.12392039927415242,
 0.12392039927415242,
 0.12392039927415242,
 0.12392039927415242,
 0.12392039927415242,
 0.12351231781710247,
 0.12309149097933275,
 0.12309149097933275,
 0.12227899701112964,
 0.12227899701112963,
 0.12227899701112963,
 0.12196734422726127,
 0.12196734422726127,
 0.12196734422726126,
 0.12087344460380703,
 0.1207011373963169,
 0.1207011373963169,
 0.1207011373963169,
 0.12060453783110546,
 0.12060453783110546,
 0.11980845957463077,
 0.11918282365569904,
 0.11918282365569904,
 0.11918282365569904,
 0.11826247919781653,
 0.11826247919781653,
 0.11776030079682895,
 0.11776030079682895,
 0.11776030079682895,
 0.11772040233700279,
 0.11725441178024137,
 0.11631052629980887,
 0.11631052629980887,
 0.1160517706371319,
 0.11495012246792571,
 0.11495012246792571,
 0.11487593716012254,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11306675421666137,
 0.11306675421666137,
 0.11306675421666137,
 0.11306675421666137,
 0.11306675421666137,
 0.11306675421666136,
 0.11306675421666136,
 0.11236664374387369,
 0.11236664374387369,
 0.11236664374387369,
 0.11236664374387369,
 0.11197850219117086,
 0.11197850219117086,
 0.11197850219117086,
 0.11113855611859677,
 0.11113855611859677,
 0.11113855611859677,
 0.11009637651263605,
 0.11009637651263605,
 0.11009637651263605,
 0.10994987428338562,
 0.1096908636190696,
 0.1096908636190696,
 0.10889310129609417,
 0.10879853497231115,
 0.10830607221477648,
 0.10770505460691618,
 0.107682623063487,
 0.107682623063487,
 0.107682623063487,
 0.107682623063487,
 0.10726454129012915,
 0.10660035817780522,
 0.10660035817780522,
 0.10660035817780522,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10586770098608782,
 0.10497277621629561,
 0.10497277621629561,
 0.10497277621629561,
 0.10497277621629561,
 0.10497277621629561,
 0.10453025125088636,
 0.1044465935734187,
 0.10444659357341869,
 0.1037571695799112,
 0.10353942082032278,
 0.10353942082032278,
 0.10353942082032278,
 0.10353942082032278,
 0.10353942082032278,
 0.10353942082032278,
 0.10341753799900383,
 0.10341753799900383,
 0.10341753799900383,
 0.10257624248277727,
 0.10257624248277727,
 0.1019294382875251,
 0.1019294382875251,
 0.1019294382875251,
 0.10176802973291377,
 0.10163945352271772,
 0.10154529930749041,
 0.10112997936948631,
 0.10112997936948631,
 0.10112997936948631,
 0.10072787050317253,
 0.10072787050317253,
 0.10072787050317253,
 0.10072787050317253,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.09988907373180403,
 0.09988907373180403,
 0.09984038297885897,
 0.09928550884822428,
 0.09927330486454494,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09897594780811197,
 0.09897594780811197,
 0.09883693657685838,
 0.09869275424396534,
 0.09869275424396534,
 0.09869275424396534,
 0.09869275424396534,
 0.09869275424396534,
 0.09813358399735746,
 0.09813358399735746,
 0.09813358399735746,
 0.09813358399735746,
 0.09811049102515929,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.09731236802019037,
 0.09656090991705352,
 0.09656090991705352,
 0.09656090991705352,
 0.09656090991705352,
 0.09656090991705352,
 0.09651142956027287,
 0.09651142956027287,
 0.09651142956027287,
 0.09642365197998373,
 0.09642365197998373,
 0.09642365197998373,
 0.09642365197998373,
 0.09642365197998373,
 0.09642365197998373,
 0.09572994763343545,
 0.09534625892455924,
 0.09534625892455924,
 0.09534625892455924,
 0.09496714704969828,
 0.09496714704969828,
 0.09430419201928972,
 0.09430419201928972,
 0.09430419201928972,
 0.09430419201928972,
 0.09422229518055114,
 0.09422229518055114,
 0.09422229518055114,
 0.09422229518055114,
 0.09422229518055114,
 0.09417632186960223,
 0.09417632186960223,
 0.09417632186960223,
 0.09417632186960223,
 0.09417632186960223,
 0.09349469900084573,
 0.09304842103984709,
 0.09304842103984709,
 0.09304842103984709,
 0.09304842103984709,
 0.09231861823449956,
 0.09231861823449956,
 0.09208868358546966,
 0.09208868358546966,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09090909090909091,
 0.09090909090909091,
 0.09090909090909091,
 0.09090909090909091,
 0.09090909090909091,
 0.09045340337332909,
 0.09045340337332909,
 0.09009374626955591,
 0.09009374626955591,
 0.08989331499509895,
 0.08989331499509895,
 0.08989331499509895,
 0.08989331499509895,
 0.08989331499509895,
 0.08945703337056415,
 0.08945703337056415,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.0888336318148377,
 0.0886968593983624,
 0.0886968593983624,
 0.0886968593983624,
 0.0886968593983624,
 0.0886968593983624,
 0.0886968593983624,
 0.0886968593983624,
 0.0886968593983624,
 0.0886968593983624,
 0.08822308415507318,
 0.0879598994267085,
 0.0879598994267085,
 0.0879598994267085,
 0.0879598994267085,
 0.0879598994267085,
 0.0876249546540977,
 0.0876249546540977,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08646430798325933,
 0.0861460984507896,
 0.0861460984507896,
 0.0861460984507896,
 0.0861460984507896,
 0.08547043234472845,
 0.08547043234472845,
 0.08547043234472845,
 0.08547043234472845,
 0.08547043234472845,
 0.08547043234472845,
 0.08547043234472845,
 0.08547043234472845,
 0.08547043234472845,
 0.08547043234472845,
 0.08534859274986485,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.0848066914440948,
 0.0844400661841498,
 0.0844400661841498,
 0.0844400661841498,
 0.0844400661841498,
 0.0844400661841498,
 0.08427498280790527,
 0.08427498280790527,
 0.08398387664337814,
 0.08398387664337814,
 0.08398387664337814,
 0.08398387664337814,
 0.08398387664337814,
 0.08398387664337814,
 0.08398387664337814,
 0.08398387664337814,
 0.08398387664337814,
 0.08375315127160099,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08283153665625823,
 0.08283153665625823,
 0.08283153665625823,
 0.0827379240401869,
 0.08257228238447704,
 0.08257228238447704,
 0.08257228238447704,
 0.08257228238447704,
 0.08257228238447704,
 0.08215419219227854,
 0.08206099398622183,
 0.08206099398622183,
 0.08206099398622183,
 0.08175874252096607,
 0.08131156281817417,
 0.08131156281817417,
 0.08131156281817417,
 0.08122955416108235,
 0.08122955416108235,
 0.08122955416108235,
 0.08122955416108235,
 0.08122955416108235,
 0.08122955416108235,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08026441628216505,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07918075824648958,
 0.07918075824648958,
 0.07901744265512675,
 0.0787295821622217,
 0.0787295821622217,
 0.0787295821622217,
 0.0787295821622217,
 0.0787295821622217,
 0.0787295821622217,
 0.07850686719788597,
 0.07850686719788597,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07733602811121826,
 0.07733602811121826,
 0.07720914364821829,
 0.07720914364821829,
 0.07658395810674837,
 0.07653459686532839,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07597371763975862,
 0.07597371763975862,
 0.07597371763975862,
 0.07597371763975862,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07500375028127344,
 0.07479575920067658,
 0.07460470969529907,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07422696190252054,
 0.07422696190252054,
 0.07367094686837573,
 0.07367094686837573,
 0.07367094686837573,
 0.07367094686837573,
 0.07367094686837573,
 0.07367094686837573,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667777,
 0.07312724241271307,
 0.07312724241271307,
 0.07312724241271307,
 0.07259540086406277,
 0.07259540086406277,
 0.07259540086406277,
 0.07242068243779014,
 0.07242068243779014,
 0.07242068243779014,
 0.07242068243779014,
 0.07207499701564472,
 0.07207499701564472,
 0.07207499701564471,
 0.07156562669645132,
 0.07156562669645132,
 0.07156562669645132,
 0.07156562669645132,
 0.07150969419341943,
 0.07150969419341943,
 0.07150969419341943,
 0.07150969419341943,
 0.07150969419341943,
 0.07150969419341943,
 0.07150969419341943,
 0.07106690545187015,
 0.07106690545187015,
 0.07106690545187015,
 0.07106690545187015,
 0.07106690545187015,
 0.07106690545187015,
 0.07106690545187015,
 0.07106690545187015,
 0.07106690545187015,
 0.07106690545187015,
 0.07063224140220167,
 0.07063224140220167,
 0.07063224140220167,
 0.07063224140220167,
 0.07063224140220167,
 0.07063224140220167,
 0.07063224140220167,
 0.07063224140220167,
 0.07063224140220167,
 0.07057846732405855,
 0.07057846732405855,
 0.07029019463944167,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06963106238227913,
 0.06963106238227913,
 0.06963106238227913,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06872081327440495,
 0.06872081327440495,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06784535315527584,
 0.06784535315527584,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06668313367115807,
 0.06668313367115805,
 0.06668313367115805,
 0.06668313367115805,
 0.06668313367115805,
 0.06668313367115805,
 0.06668313367115805,
 0.06668313367115805,
 0.06668313367115805,
 0.06619033923214952,
 0.06596992457003137,
 0.06596992457003137,
 0.06596992457003137,
 0.06596992457003137,
 0.06596992457003137,
 0.06596992457003137,
 0.06596992457003137,
 0.06596992457003137,
 0.06596992457003137,
 0.06596992457003137,
 0.06596992457003137,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.06502560887623551,
 0.06465081838352359,
 0.06460957383809221,
 0.06460957383809221,
 0.06460957383809221,
 0.06460957383809221,
 0.06460957383809221,
 0.06460957383809221,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06396021490668313,
 0.06396021490668313,
 0.06396021490668313,
 0.06396021490668313,
 0.06396021490668313,
 0.06396021490668313,
 0.06396021490668313,
 0.06333004963811235,
 0.06333004963811235,
 0.06333004963811235,
 0.06333004963811235,
 0.06333004963811235,
 0.06333004963811235,
 0.06333004963811235,
 0.06333004963811235,
 0.06333004963811235,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.062197041357112286,
 0.06212365249219367,
 0.06212365249219367,
 0.06212365249219367,
 0.06212365249219367,
 0.06212365249219367,
 0.06212365249219367,
 0.06212365249219367,
 0.06212365249219367,
 0.06212365249219367,
 0.06212365249219367,
 0.061545745489666376,
 0.061545745489666376,
 0.061545745489666376,
 0.061545745489666376,
 0.061545745489666376,
 0.061545745489666376,
 0.061545745489666376,
 0.061545745489666376,
 0.061545745489666376,
 0.061545745489666376,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06122767749226271,
 0.06098367211363063,
 0.06098367211363063,
 0.06098367211363063,
 0.06098367211363063,
 0.06098367211363063,
 0.06098367211363063,
 0.06091449038731726,
 0.06054493496206034,
 0.06043672230190352,
 0.06043672230190352,
 0.06043672230190352,
 0.06043672230190352,
 0.06043672230190352,
 0.06043672230190352,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.060003000225018754,
 0.05990422978731538,
 0.05990422978731538,
 0.05990422978731538,
 0.05990422978731538,
 0.05990422978731538,
 0.05990422978731538,
 0.05938556868486719,
 0.05938556868486719,
 0.05938556868486719,
 0.05938556868486719,
 0.05938556868486719,
 0.05938556868486719,
 0.05938556868486719,
 0.059385568684867183,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.058880150398414474,

In [59]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [60]:
recommend('Batman Begins')

The Dark Knight
Batman
The Dark Knight Rises
Batman
Rockaway

In [61]:
new_df.iloc[1216].title

'Aliens vs Predator: Requiem'

In [62]:
import pickle

In [63]:
pickle.dump(new_df, open('movies.pkl', 'wb'))

In [65]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [66]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [68]:
movies_list = pickle.load(open('movies.pkl', 'rb'))

In [69]:
movies_list

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bondâ€™ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4805,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4807,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4808,25975,My Date with Drew,ever sinc the second grade when he first saw h...